-- Generated by nwg-displays on 2026-08-07 at 17:43:07. Do not edit manually.

hl.monitor({
  name = "DP-2",
  width = 3840,
  height = 2160,
  refreshRate = 70.0,
  x = 0,
  y = 0,
  scale = 1.5000000000000004,
  bitdepth = 10,
})

hl.monitor({
  name = "DP-1",
  width = 2560,
  height = 1440,
  refreshRate = 165.08,
  x = 2560,
  y = 0,
  scale = 1.0,
  bitdepth = 10,
})
