# --- Font Configuration ---
font_family      JetBrainsMono Nerd Font
font_size        18.0

# --- Theme Link ---
include theme.conf

# --- Window Customization ---
window_padding_width 8
background_opacity 0.90
dynamic_background_opacity yes

# --- Terminal Bell ---
enable_audio_bell no

# --- Scrollback ---
scrollback_lines 10000

# --- Keybindings ---
# Reload configuration dynamically
map ctrl+shift+f5 load_config_file
map ctrl+backspace send_text all \x1b\x7f

map shift+left no_op
map shift+right no_op
map shift+up no_op
map shift+down no_op
report_keyboard_events no
