$hypr = ~/.config/hypr


$hl = $hypr/hyprland
$cConf = ~/.config/caelestia

# Variables (colours + other vars)
exec = cp -L --no-preserve=mode --update=none $hypr/scheme/default.conf $hypr/scheme/current.conf
source = $hypr/scheme/current.conf
source = $hypr/variables.conf

# Maybe create hyprland configs
exec = $hypr/scripts/configs.fish $cConf

# User variables
source = $cConf/hypr-vars.conf

# Default monitor conf
monitor = , preferred, auto, 1

# Configs
source = ~/.config/hypr/hyprland/env.conf
source = ~/.config/hypr/hyprland/general.conf
source = ~/.config/hypr/hyprland/input.conf
source = ~/.config/hypr/hyprland/misc.conf
source = ~/.config/hypr/hyprland/animations.conf
source = ~/.config/hypr/hyprland/decoration.conf
source = ~/.config/hypr/hyprland/group.conf
source = ~/.config/hypr/hyprland/execs.conf
source = ~/.config/hypr/hyprland/rules.conf
source = ~/.config/hypr/hyprland/gestures.conf
source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/scrolling.conf
source = ~/.config/hypr/monitors.conf

# User configs
source = $cConf/hypr-user.conf

