-- Generated by nwg-displays on 2026-07-18 at 16:56:38. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.0
})
