# --- Clipboard (xclip) ---
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# --- Launch dev session ---
bind D if-shell "tmux has-session -t dev 2>/dev/null" \
  "switch-client -t dev" \
  "new-session -s dev -n term -d \; \
   new-window -t dev:2 -n nvim \; send-keys -t dev:2 'cd .config/nvim/ && nvim lua/plugins/' Enter \; \
   new-window -t dev:3 -n opencode \; send-keys -t dev:3 'opencode' Enter \; split-window -h -t dev:3 \; send-keys -t dev:3 'opencode' Enter \; \
   select-window -t dev:1 \; switch-client -t dev"

# --- Popup terminal (current dir) ---
bind o display-popup -E -w 98% -h 98% -d "#{pane_current_path}"
bind g display-popup -E -w 98% -h 98% -d "#{pane_current_path}" nvim -c "lua vim.defer_fn(function() vim.cmd('Neogit') end, 500)"
bind e display-popup -E -w 98% -h 98% -d send-keys "nvim ~/.tmux.conf"
bind v display-popup -E -w 98% -h 98% -d send-keys "nvim ~/.config/nvim/lua/plugins/"

bind-key j break-pane
